### ISSUE TITLE
Basic examples are responding with errors 

### ISSUE THREAD

**Issue by sebs** [Profiscience/ko-component-tester#30]
This file in /test

```js
'use strict'
const { renderHtml } = require('ko-component-tester')
```

with the following package.json

```json
{
  "name": "knockout-tests",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "mocha"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "jquery": "^2.2.0",
    "knockout": "^3.4.2",
    "ko-component-tester": "^3.2.1"
  }
}
```

gives errors

```shell 

> knockout-tests@1.0.0 test /Users/sebs/projects/customers/sumcumo/knockout-tests
> mocha

/Users/sebs/projects/..../knockout-tests/node_modules/ko-component-tester/dist/ko-component-tester.js:67
	$.fn.simulate = function (eventName, value) {
	              ^

TypeError: Cannot set property 'simulate' of undefined
    at Object.module.exports (....
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**Comment by sebs** [comment]
➜  knockout-tests npm  -v          
3.10.3
➜  knockout-tests node -v
v6.7.0
➜  knockout-tests
